name: Deploy

on:
    workflow_run:
        workflows: ["Build"]
        branches: [main]
        types:
            - completed

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        permissions:
            actions: write

        steps:
            - name: Download artifact
              uses: dawidd6/action-download-artifact@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  workflow: build.yml
                  workflow_conclusion: success
                  name: production-files
                  path: ./dist

            - name: Deploy to Staging server
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: "-z --delete"
                  SOURCE: 'dist/'
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: ${{ secrets.REMOTE_TARGET }}
                  EXCLUDE: '/node_modules/'
