name: Deploy
run-name: 'Deploy "${{ github.event.workflow_run.head_commit.message }}" #${{ github.run_attempt }}'

on:
    workflow_run:
        workflows: ['Build']
        branches: [main]
        types:
            - completed

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        if: "${{ github.ref == 'refs/heads/main' && !startsWith(github.event.workflow_run.head_commit.message, 'dev') && !startsWith(github.event.workflow_run.head_commit.message, 'docs') }}"
        permissions:
            actions: write

        steps:
            - name: Download artifact
              uses: dawidd6/action-download-artifact@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  workflow: build.yml
                  workflow_conclusion: success
                  name: production-files
                  path: ./dist

            - name: Deploy
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: '-z --delete'
                  SOURCE: 'dist/'
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: ${{ secrets.REMOTE_TARGET }}
                  EXCLUDE: '/node_modules/'
